Feat/#25 revise page2
hangeul-project/hangeul-react-web pull request #49
Opened 2021-09-06 02:39 UTC by junho7359

1. Page2 AOS 조정
2. Page1&Page2 미디어 쿼리 조정

console 오류 나는 부분 주석 처리 했으니 참고해주세요

2021-09-06 04:31 UTC, SaraHan774 commented
현재 Pull Request 요청받는 base 브랜치가 main 으로 설정되어 있는데, 우측 상단에 타이틀 옆에 edit 버튼 눌러서 base 를 develop 으로 수정해 줘야해 ! 그리고 git fetch origin 해서 원격 변경사항 반영시키고 git pull origin develop 해서 준호 작업한거랑 충돌 나는지 안나는지 확인도 해야돼영

2021-09-06 04:31 UTC, SaraHan774 requested changes
base 브랜치 변경하고, 현재 develop 에 있는거 여기 피처브랜치에 땡겨온 후에 다시 commit push 해주세용

2021-09-06 05:23 UTC, zinozzing commented
base 브랜치 develop으로 바꿔주세요

2021-09-06 05:38 UTC, zinozzing approved these changes

2021-09-06 05:48 UTC, SaraHan774 requested changes

2021-09-06 05:48 UTC, SaraHan774 commented on .eslintrc.js
> +      { "no-console": "off" },
밑에거 어쩌다가 지워졌나요 ? 요 세팅이랑 동일한거같은데

2021-09-06 05:48 UTC, SaraHan774 commented on src/component/Page1/Page1.css
> +body{
body 처럼 태크 자체에 스타일링 적용하는 거 있으면 Page1.css 처럼 특정 컴포넌트의 css 로 넣지 말고, GlobalStyle.css 같은 파일 하나 새로 만들어서, 이 파일을 App.js 에 임포트 시켜 놓는게 깔끔할거같아요

2021-09-06 05:48 UTC, SaraHan774 commented on src/component/Page3/UI/AnswerButton.js
> -  hasBeenSolved: PropTypes.bool.isRequired,
사용되지 않은 변수더라도 삭제되면 안되는데, 이 부분 다시 rollback 해주시고, eslintrc 에도 기존 린트 규칙대로 변경 부탁드려요 ! 
"no-unused-vars": "off" 이게 사용되지 않은 변수에 대해 린트 에러 나지 않도록 하라는 규칙이에요.

2021-09-06 05:48 UTC, SaraHan774 commented on src/component/Page3/UI/AnswerButton.js
> +const AnswerButton = ({ answerId, answerText, onSelectionChange }) => {
hasBeenSolved 가 삭제되어서 줄바꿈이 일어났는데 이부분도 원래처럼 수정 부탁드려요

2021-09-06 05:48 UTC, SaraHan774 commented on src/component/Page3/UI/QuizContainer.js
> +  const onQuizFinished = () => {
여기서도 지금 "no-unused-vars": "off" 옵션 삭제되어서 event 매개변수가 지워졌네요

2021-09-06 05:54 UTC, junho7359 commented on .eslintrc.js
> +      { "no-console": "off" },
콘솔로그 부분 때문에 이것저것 해보다가 그런 것 같아요..

2021-09-06 05:54 UTC, junho7359 commented on src/component/Page1/Page1.css
> +body{
이 부분 container에 넣도록 하겠습니다

2021-09-06 06:09 UTC, SaraHan774 commented on .eslintrc.js
> +        extensions: [".js", ".jsx", ".ts", ".tsx"],
이거는 어쩌다가 추가된거징 ?

2021-09-06 06:12 UTC, SaraHan774 commented on src/component/Page1/Page1.css
> +body{
수정하시고 Resolve Conversation 버튼 클릭 해주세용 ~

2021-09-06 07:02 UTC, SaraHan774 requested changes

2021-09-06 07:02 UTC, SaraHan774 commented on .eslintrc.js
> -    "no-console": "off",
여기 삭제된 두 줄 다시 넣고, 위에 { no-console : off } 한거 지우면 돼 !

2021-09-06 07:18 UTC, junho7359 commented on .eslintrc.js
> +        extensions: [".js", ".jsx", ".ts", ".tsx"],
오류 나서 찾아보니 넣으면 된다고해서.. 지금 빼도 실행 되서 삭제했습니다!

2021-09-06 07:20 UTC, zinozzing commented on .eslintrc.js
> +        extensions: [".js", ".jsx", ".ts", ".tsx"],
빼지말고 주석처리해주세요

2021-09-06 07:44 UTC, kim-soo commented on src/component/Page1/Page1.css
> +    margin-left:72vw;
요런 식으로 space 없어진거 lint 변경해서 그런건가요?

2021-09-06 07:45 UTC, kim-soo commented on src/component/Page1/Page1.css
> +@media(max-width:440px){
요게 미디어 쿼리로 모바일 버전 보는건가요?

2021-09-06 07:48 UTC, kim-soo reviewed
css 바뀐 거 확인했어요 css file에 : 사이로 space 없어진 거 lint 수정한 문젠가요? 이거 혹시 머지했을 때 일반적으로 모두에게 적용되는 건지 궁금하네요 지금 가희 언니가 린트 수정한 게 그 부분인지도 궁금하구 ...

2021-09-06 09:40 UTC, SaraHan774 commented on src/component/Page1/Page1.css
> +    margin-left:72vw;
내가 수정한 린트랑은 다른 문제인거같아 ! 이런 포맷 변경은 되도록이면 준호쪽에서 원래대로 ( 콜론 다음에 스페이스바 넣는 형식으로) 맞춰줘야 할텐데

2021-09-06 12:23 UTC, zinozzing commented on src/component/Page1/Page1.css
> +@media(max-width:440px){
가로 사이즈가 440px 이하인 기기에서 보여지는 부분을 맡은거에요
보통 모바일 사이즈가 그정도니까 이해한게 맞습니당

2021-09-06 12:26 UTC, zinozzing commented on src/component/Page1/Page1.css
> +    margin-left:72vw;
lint 문제는 아닌거같고, 누나 말대로 포맷은 직접 맞춰주거나 프리티어 같은 확장팩을 통해 통일 시켜주는게 맞을 것 같아요!

2021-09-06 12:33 UTC, zinozzing reviewed
전체적으로 수정해서 다시 커밋해주세요~

2021-09-06 12:33 UTC, zinozzing commented on src/component/Page1/Page1.css
> +    margin-left:72vw;
그러게 스페이스 때문에 한줄 한줄이 다 변경된걸로 되어버렸네 ㅠㅠ

2021-09-06 12:33 UTC, zinozzing commented on src/shared/App.js
> -        {/* <Page4 /> */}
여기 주석 왜 지워졌나요? ㅠㅠ

2021-09-06 12:36 UTC, zinozzing commented
전체적으로 수정후 다시 커밋해주세요!

2021-09-06 12:37 UTC, zinozzing requested changes
전체적인 수정 부탁드립니다~

2021-09-07 01:08 UTC, junho7359 commented on src/component/Page1/Page1.css
> +    margin-left:72vw;
스페이스바 다시 넣어서 수정하겠습니다!

2021-09-07 01:08 UTC, junho7359 commented on src/shared/App.js
> -        {/* <Page4 /> */}
죄송합니다 ㅠ 다시 추가할게요

2021-09-07 01:24 UTC, zinozzing approved these changes
수고했어요~!

2021-09-07 03:41 UTC, SaraHan774 approved these changes

2021-09-07 06:15 UTC, merged